# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_event_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='distance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
