# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20170120_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
